/********************************************************************
* online/G__online.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error online/G__online.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__online();
extern void G__cpp_setup_inheritanceG__online();
extern void G__cpp_setup_typetableG__online();
extern void G__cpp_setup_memvarG__online();
extern void G__cpp_setup_globalG__online();
extern void G__cpp_setup_memfuncG__online();
extern void G__cpp_setup_funcG__online();
extern void G__set_cpp_environmentG__online();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "online/TSnIOBuffer.h"
#include "online/TSnIOObject.h"
#include "online/TSnIOConfigFrame.h"
#include "online/TSnIOEventFrame.h"
#include "online/TSnIOStatusFrame.h"
#include "online/TSnIOHeaderFrame.h"
#include "online/TSnIOHeartbeatFrame.h"
#include "online/TSnIOPowerFrame.h"
#include "online/TSnIOClockSetFrame.h"
#include "online/TSnIOSignalStrengthFrame.h"
#include "online/TSnIODataFile.h"
#include "online/TSnCommObject.h"
#include "online/TSnCommQueue.h"
#include "online/TSnCommConfPack.h"
#include "online/TSnCommMbedLocalFile.h"
#include "online/TSnCommStatusPack.h"
#include "online/TSnCommAlertPack.h"
#include "online/TSnCommIncoming.h"
#include "online/TSnCommIncFile.h"
#include "online/TSnCommIncStatus.h"
#include "online/TSnCommIncHandshake.h"
#include "online/TSnCommProtocolMsg.h"
#include "online/TSnCommDeleteDataMsg.h"
#include "online/TSnCommActor.h"
#include "online/TSnCommAction.h"
#include "online/TSnCommStatusAction.h"
#include "online/TSnCommFileAction.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__onlineLN_TClass;
extern G__linked_taginfo G__G__onlineLN_TBuffer;
extern G__linked_taginfo G__G__onlineLN_TMemberInspector;
extern G__linked_taginfo G__G__onlineLN_TObject;
extern G__linked_taginfo G__G__onlineLN_TNamed;
extern G__linked_taginfo G__G__onlineLN_TString;
extern G__linked_taginfo G__G__onlineLN_vectorlEcharcOallocatorlEchargRsPgR;
extern G__linked_taginfo G__G__onlineLN_vectorlEcharcOallocatorlEchargRsPgRcLcLiterator;
extern G__linked_taginfo G__G__onlineLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__G__onlineLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__G__onlineLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__onlineLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__onlineLN_TList;
extern G__linked_taginfo G__G__onlineLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__onlineLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__onlineLN_TSnCommObject;
extern G__linked_taginfo G__G__onlineLN_TSnIOBuffer;
extern G__linked_taginfo G__G__onlineLN_TTimeStamp;
extern G__linked_taginfo G__G__onlineLN_TSnIOObject;
extern G__linked_taginfo G__G__onlineLN_vectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgR;
extern G__linked_taginfo G__G__onlineLN_reverse_iteratorlEvectorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcOallocatorlEvectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__onlineLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__onlineLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__onlineLN_TMap;
extern G__linked_taginfo G__G__onlineLN_TSnDAQConfig;
extern G__linked_taginfo G__G__onlineLN_TSnRunInfo;
extern G__linked_taginfo G__G__onlineLN_TSnNetAdrSet;
extern G__linked_taginfo G__G__onlineLN_TSnIOConfigFrame;
extern G__linked_taginfo G__G__onlineLN_TSnIOEventFrame;
extern G__linked_taginfo G__G__onlineLN_TSnEvent;
extern G__linked_taginfo G__G__onlineLN_TSnStatusUpdate;
extern G__linked_taginfo G__G__onlineLN_TSnIOStatusFrame;
extern G__linked_taginfo G__G__onlineLN_TSnIOHeaderFrame;
extern G__linked_taginfo G__G__onlineLN_TSnIOHeartbeatFrame;
extern G__linked_taginfo G__G__onlineLN_TSnPowerReading;
extern G__linked_taginfo G__G__onlineLN_TSnIOPowerFrame;
extern G__linked_taginfo G__G__onlineLN_TSnClockSetInfo;
extern G__linked_taginfo G__G__onlineLN_TSnIOClockSetFrame;
extern G__linked_taginfo G__G__onlineLN_TSnSignalStrengthInfo;
extern G__linked_taginfo G__G__onlineLN_TSnIOSignalStrengthFrame;
extern G__linked_taginfo G__G__onlineLN_TSnCompMbed;
extern G__linked_taginfo G__G__onlineLN_TSnHeartbeat;
extern G__linked_taginfo G__G__onlineLN_TSnIODataFile;
extern G__linked_taginfo G__G__onlineLN_TSnCommQueue;
extern G__linked_taginfo G__G__onlineLN_TSnCommConfPack;
extern G__linked_taginfo G__G__onlineLN_TSnCommMbedLocalFile;
extern G__linked_taginfo G__G__onlineLN_TSnCommStatusPack;
extern G__linked_taginfo G__G__onlineLN_TSnCommAlertPack;
extern G__linked_taginfo G__G__onlineLN_TSnCommAlertPackcLcLESeverity;
extern G__linked_taginfo G__G__onlineLN_TSnCommIncoming;
extern G__linked_taginfo G__G__onlineLN_TSnCommIncFile;
extern G__linked_taginfo G__G__onlineLN_TSnCommIncStatus;
extern G__linked_taginfo G__G__onlineLN_TSnCommIncHandshake;
extern G__linked_taginfo G__G__onlineLN_TSnCommProtocolMsg;
extern G__linked_taginfo G__G__onlineLN_TSnCommDeleteDataMsg;
extern G__linked_taginfo G__G__onlineLN_TIterator;
extern G__linked_taginfo G__G__onlineLN_TObjLink;
extern G__linked_taginfo G__G__onlineLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__onlineLN_TSnCommAction;
extern G__linked_taginfo G__G__onlineLN_TSnCommActor;
extern G__linked_taginfo G__G__onlineLN_TRef;
extern G__linked_taginfo G__G__onlineLN_TSnCommStatusAction;
extern G__linked_taginfo G__G__onlineLN_TSnCommFileAction;

/* STUB derived class for protected member access */
