/********************************************************************
* recodat/G__recodat.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error recodat/G__recodat.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__recodat();
extern void G__cpp_setup_inheritanceG__recodat();
extern void G__cpp_setup_typetableG__recodat();
extern void G__cpp_setup_memvarG__recodat();
extern void G__cpp_setup_globalG__recodat();
extern void G__cpp_setup_memfuncG__recodat();
extern void G__cpp_setup_funcG__recodat();
extern void G__set_cpp_environmentG__recodat();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "recodat/TSnRecoResult.h"
#include "recodat/TSnRecoDirection.h"
#include "recodat/TSnRecoChanOffsets.h"
#include "recodat/TSnRecoSingleChanOffset.h"
#include "recodat/TSnRecoSingleChanOffsetSet.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__recodatLN_TClass;
extern G__linked_taginfo G__G__recodatLN_TBuffer;
extern G__linked_taginfo G__G__recodatLN_TMemberInspector;
extern G__linked_taginfo G__G__recodatLN_TObject;
extern G__linked_taginfo G__G__recodatLN_TNamed;
extern G__linked_taginfo G__G__recodatLN_TString;
extern G__linked_taginfo G__G__recodatLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__recodatLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__recodatLN_TObjArray;
extern G__linked_taginfo G__G__recodatLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__recodatLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__recodatLN_TSnRecoResult;
extern G__linked_taginfo G__G__recodatLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__recodatLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__recodatLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__recodatLN_TVector3;
extern G__linked_taginfo G__G__recodatLN_TSnRecoDirection;
extern G__linked_taginfo G__G__recodatLN_TArrayD;
extern G__linked_taginfo G__G__recodatLN_TSnRecoChanOffsets;
extern G__linked_taginfo G__G__recodatLN_TSnRecoSingleChanOffset;
extern G__linked_taginfo G__G__recodatLN_TSnRecoSingleChanOffsetSet;

/* STUB derived class for protected member access */
