/********************************************************************
* tam/G__tam.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tam/G__tam.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__tam();
extern void G__cpp_setup_inheritanceG__tam();
extern void G__cpp_setup_typetableG__tam();
extern void G__cpp_setup_memvarG__tam();
extern void G__cpp_setup_globalG__tam();
extern void G__cpp_setup_memfuncG__tam();
extern void G__cpp_setup_funcG__tam();
extern void G__set_cpp_environmentG__tam();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "tam/TAMBranchInfo.h"
#include "tam/TAMObjBranchLoader.h"
#include "tam/TAMObjLoader.h"
#include "tam/TAModule.h"
#include "tam/TAMOutput.h"
#include "tam/TAMSelector.h"
#include "tam/TAMTreeBranchLoader.h"
#include "tam/TAMTreeLoader.h"
#include "tam/TAMVirtualBranchLoader.h"
#include "tam/TAMVirtualLoader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__tamLN_type_info;
extern G__linked_taginfo G__G__tamLN_TClass;
extern G__linked_taginfo G__G__tamLN_TBuffer;
extern G__linked_taginfo G__G__tamLN_TMemberInspector;
extern G__linked_taginfo G__G__tamLN_TObject;
extern G__linked_taginfo G__G__tamLN_TNamed;
extern G__linked_taginfo G__G__tamLN_TCollection;
extern G__linked_taginfo G__G__tamLN_TString;
extern G__linked_taginfo G__G__tamLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__tamLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__tamLN_TList;
extern G__linked_taginfo G__G__tamLN_TBrowser;
extern G__linked_taginfo G__G__tamLN_TProcessID;
extern G__linked_taginfo G__G__tamLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__tamLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__tamLN_TPRegexp;
extern G__linked_taginfo G__G__tamLN_TTree;
extern G__linked_taginfo G__G__tamLN_TAMVirtualBranchLoader;
extern G__linked_taginfo G__G__tamLN_TAMBranchInfo;
extern G__linked_taginfo G__G__tamLN_vectorlETAMBranchInfocLcLBranchPtr_tmUcOallocatorlETAMBranchInfocLcLBranchPtr_tmUgRsPgR;
extern G__linked_taginfo G__G__tamLN_reverse_iteratorlEvectorlETAMBranchInfocLcLBranchPtr_tmUcOallocatorlETAMBranchInfocLcLBranchPtr_tmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__tamLN_TAMObjBranchLoader;
extern G__linked_taginfo G__G__tamLN_TAMVirtualLoader;
extern G__linked_taginfo G__G__tamLN_TAMObjLoader;
extern G__linked_taginfo G__G__tamLN_TSeqCollection;
extern G__linked_taginfo G__G__tamLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__tamLN_TTask;
extern G__linked_taginfo G__G__tamLN_TSelector;
extern G__linked_taginfo G__G__tamLN_THashTable;
extern G__linked_taginfo G__G__tamLN_TBranch;
extern G__linked_taginfo G__G__tamLN_TFile;
extern G__linked_taginfo G__G__tamLN_TAModule;
extern G__linked_taginfo G__G__tamLN_TAMOutput;
extern G__linked_taginfo G__G__tamLN_TAMSelector;
extern G__linked_taginfo G__G__tamLN_TAMSelectorcLcLBranchProxy;
extern G__linked_taginfo G__G__tamLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__tamLN_TAMOutputcLcLTAMModInspector;
extern G__linked_taginfo G__G__tamLN_TAMOutputcLcLTAMModInspectorcLcLTAMModMember;
extern G__linked_taginfo G__G__tamLN_vectorlETIteratormUcOallocatorlETIteratormUgRsPgR;
extern G__linked_taginfo G__G__tamLN_reverse_iteratorlEvectorlETIteratormUcOallocatorlETIteratormUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__tamLN_TAModulecLcLEModResult;
extern G__linked_taginfo G__G__tamLN_TDataType;
extern G__linked_taginfo G__G__tamLN_TAMTreeBranchLoader;
extern G__linked_taginfo G__G__tamLN_TAMTreeLoader;

/* STUB derived class for protected member access */
