/********************************************************************
* loaders/G__loaders.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error loaders/G__loaders.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__loaders();
extern void G__cpp_setup_inheritanceG__loaders();
extern void G__cpp_setup_typetableG__loaders();
extern void G__cpp_setup_memvarG__loaders();
extern void G__cpp_setup_globalG__loaders();
extern void G__cpp_setup_memfuncG__loaders();
extern void G__cpp_setup_funcG__loaders();
extern void G__set_cpp_environmentG__loaders();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "loaders/TSnLinkedTreeBranchLoader.h"
#include "loaders/TSnMetadataLinkBranchLoader.h"
#include "loaders/TSnTimeLinkBranchLoader.h"
#include "loaders/TSnConfigTreeLoader.h"
#include "loaders/TSnVoltageTreeLoader.h"
#include "loaders/TSnHeartbeatTreeLoader.h"
#include "loaders/TSnVoltageBranchLoader.h"
#include "loaders/TSnHeartbeatBranchLoader.h"
#include "loaders/TSnAltTreeLoader.h"
#include "loaders/TSnAltTreeBranchLoader.h"
#include "loaders/TSnAltTreeRandomLoader.h"
#include "loaders/TSnAltTreeCyclicLoader.h"
#include "loaders/TSnAltTreeShuffleLoader.h"
#include "loaders/TSnAltTreeSingleEntryLoader.h"
#include "loaders/TSnLoadFromFileMod.h"
#include "loaders/TSnWindTreeLoader.h"
#include "loaders/TSnWindBranchLoader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__loadersLN_TClass;
extern G__linked_taginfo G__G__loadersLN_TBuffer;
extern G__linked_taginfo G__G__loadersLN_TMemberInspector;
extern G__linked_taginfo G__G__loadersLN_TObject;
extern G__linked_taginfo G__G__loadersLN_TNamed;
extern G__linked_taginfo G__G__loadersLN_TString;
extern G__linked_taginfo G__G__loadersLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__loadersLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__loadersLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__loadersLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__loadersLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__loadersLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__loadersLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__loadersLN_TTree;
extern G__linked_taginfo G__G__loadersLN_TBranch;
extern G__linked_taginfo G__G__loadersLN_TAMVirtualBranchLoader;
extern G__linked_taginfo G__G__loadersLN_TAMBranchInfo;
extern G__linked_taginfo G__G__loadersLN_vectorlETAMBranchInfocLcLBranchPtr_tmUcOallocatorlETAMBranchInfocLcLBranchPtr_tmUgRsPgR;
extern G__linked_taginfo G__G__loadersLN_reverse_iteratorlEvectorlETAMBranchInfocLcLBranchPtr_tmUcOallocatorlETAMBranchInfocLcLBranchPtr_tmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__loadersLN_TAMTreeBranchLoader;
extern G__linked_taginfo G__G__loadersLN_TSnLinkedTreeBranchLoader;
extern G__linked_taginfo G__G__loadersLN_TSnEventMetadata;
extern G__linked_taginfo G__G__loadersLN_TSnMetadataLinkBranchLoader;
extern G__linked_taginfo G__G__loadersLN_TTimeStamp;
extern G__linked_taginfo G__G__loadersLN_TSnTimeLinkBranchLoader;
extern G__linked_taginfo G__G__loadersLN_TSnTimeLinkBranchLoadercLcLEMethod_t;
extern G__linked_taginfo G__G__loadersLN_TAMVirtualLoader;
extern G__linked_taginfo G__G__loadersLN_TSnConfigTreeLoader;
extern G__linked_taginfo G__G__loadersLN_TSnVoltageTreeLoader;
extern G__linked_taginfo G__G__loadersLN_TSnHeartbeatTreeLoader;
extern G__linked_taginfo G__G__loadersLN_TSnPowerReading;
extern G__linked_taginfo G__G__loadersLN_TSnEventHeader;
extern G__linked_taginfo G__G__loadersLN_TSnVoltageBranchLoader;
extern G__linked_taginfo G__G__loadersLN_TSnHeartbeat;
extern G__linked_taginfo G__G__loadersLN_TSnHeartbeatBranchLoader;
extern G__linked_taginfo G__G__loadersLN_TEntryList;
extern G__linked_taginfo G__G__loadersLN_TSnAltTreeLoader;
extern G__linked_taginfo G__G__loadersLN_TSnAltTreeBranchLoader;
extern G__linked_taginfo G__G__loadersLN_TRandom3;
extern G__linked_taginfo G__G__loadersLN_TSnAltTreeRandomLoader;
extern G__linked_taginfo G__G__loadersLN_TSnAltTreeCyclicLoader;
extern G__linked_taginfo G__G__loadersLN_TSnAltTreeShuffleLoader;
extern G__linked_taginfo G__G__loadersLN_TSnAltTreeSingleEntryLoader;
extern G__linked_taginfo G__G__loadersLN_TTask;
extern G__linked_taginfo G__G__loadersLN_TAModule;
extern G__linked_taginfo G__G__loadersLN_vectorlETIteratormUcOallocatorlETIteratormUgRsPgR;
extern G__linked_taginfo G__G__loadersLN_reverse_iteratorlEvectorlETIteratormUcOallocatorlETIteratormUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__loadersLN_TSnLoadFromFileMod;
extern G__linked_taginfo G__G__loadersLN_TSnWindTreeLoader;
extern G__linked_taginfo G__G__loadersLN_TSnWindData;
extern G__linked_taginfo G__G__loadersLN_TSnWindBranchLoader;

/* STUB derived class for protected member access */
