/********************************************************************
* sigproc/G__sigproc.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error sigproc/G__sigproc.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__sigproc();
extern void G__cpp_setup_inheritanceG__sigproc();
extern void G__cpp_setup_typetableG__sigproc();
extern void G__cpp_setup_memvarG__sigproc();
extern void G__cpp_setup_globalG__sigproc();
extern void G__cpp_setup_memfuncG__sigproc();
extern void G__cpp_setup_funcG__sigproc();
extern void G__set_cpp_environmentG__sigproc();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "sigproc/TSnRawTreeMaker.h"
#include "sigproc/TSnBasicEvtSelMod.h"
#include "sigproc/TSnRejectBadClocksMod.h"
#include "sigproc/TSnRejectEarlyEvtsMod.h"
#include "sigproc/TSnFPNCalcMod.h"
#include "sigproc/TSnFPNSubMod.h"
#include "sigproc/TSnDigitizerCalibMod.h"
#include "sigproc/TSnSaveCalibDataMod.h"
#include "sigproc/TSnCalcAbsTimeMod.h"
#include "sigproc/TSnFindTimeLimitsMod.h"
#include "sigproc/TSnFindEvtNumLimitsMod.h"
#include "sigproc/TSnPlotEvtRateMod.h"
#include "sigproc/TSnPlotWaveformsMod.h"
#include "sigproc/TSnEvtGuiCanvFrame.h"
#include "sigproc/TSnEvtGuiMainFrame.h"
#include "sigproc/TSnEvtGuiSeleFrame.h"
#include "sigproc/TSnGCanvasSaveDialog.h"
#include "sigproc/TSnEvtGuiDataGuru.h"
#include "sigproc/TSnRejectBadVoltTimesMod.h"
#include "sigproc/TSnPlotPowerReadingsMod.h"
#include "sigproc/TSnPlotAdcDists.h"
#include "sigproc/TSnCalDatModule.h"
#include "sigproc/TSnFilterWaveformMod.h"
#include "sigproc/TSnStopFindRms.h"
#include "sigproc/TSnShiftCalWvDataMod.h"
#include "sigproc/TSnMakeShiftTree.h"
#include "sigproc/TSnPruneBadEvtsMod.h"
#include "sigproc/TSnFFTCalcMod.h"
#include "sigproc/TSnFindWaveformEnvelopeMod.h"
#include "TParameter.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__sigprocLN_TClass;
extern G__linked_taginfo G__G__sigprocLN_TBuffer;
extern G__linked_taginfo G__G__sigprocLN_TMemberInspector;
extern G__linked_taginfo G__G__sigprocLN_TObject;
extern G__linked_taginfo G__G__sigprocLN_TNamed;
extern G__linked_taginfo G__G__sigprocLN_TCollection;
extern G__linked_taginfo G__G__sigprocLN_TString;
extern G__linked_taginfo G__G__sigprocLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__G__sigprocLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__sigprocLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__sigprocLN_TList;
extern G__linked_taginfo G__G__sigprocLN_TObjArray;
extern G__linked_taginfo G__G__sigprocLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__sigprocLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__sigprocLN_TFile;
extern G__linked_taginfo G__G__sigprocLN_TTree;
extern G__linked_taginfo G__G__sigprocLN_TSnDAQConfig;
extern G__linked_taginfo G__G__sigprocLN_TSnRunInfo;
extern G__linked_taginfo G__G__sigprocLN_TSnNetAdrSet;
extern G__linked_taginfo G__G__sigprocLN_TSnCompMbed;
extern G__linked_taginfo G__G__sigprocLN_TSnEvent;
extern G__linked_taginfo G__G__sigprocLN_TSnPowerReading;
extern G__linked_taginfo G__G__sigprocLN_TSnHeartbeat;
extern G__linked_taginfo G__G__sigprocLN_TSnClockSetInfo;
extern G__linked_taginfo G__G__sigprocLN_TSnEventMetadata;
extern G__linked_taginfo G__G__sigprocLN_TSnRawTreeMaker;
extern G__linked_taginfo G__G__sigprocLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__sigprocLN_TTask;
extern G__linked_taginfo G__G__sigprocLN_THashTable;
extern G__linked_taginfo G__G__sigprocLN_vectorlETAMBranchInfocLcLBranchPtr_tmUcOallocatorlETAMBranchInfocLcLBranchPtr_tmUgRsPgR;
extern G__linked_taginfo G__G__sigprocLN_reverse_iteratorlEvectorlETAMBranchInfocLcLBranchPtr_tmUcOallocatorlETAMBranchInfocLcLBranchPtr_tmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__sigprocLN_TBranch;
extern G__linked_taginfo G__G__sigprocLN_TAModule;
extern G__linked_taginfo G__G__sigprocLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__sigprocLN_vectorlETIteratormUcOallocatorlETIteratormUgRsPgR;
extern G__linked_taginfo G__G__sigprocLN_reverse_iteratorlEvectorlETIteratormUcOallocatorlETIteratormUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__sigprocLN_TSnTrgInfo;
extern G__linked_taginfo G__G__sigprocLN_TSnEventHeader;
extern G__linked_taginfo G__G__sigprocLN_TSnRawWaveform;
extern G__linked_taginfo G__G__sigprocLN_TSnBasicEvtSelMod;
extern G__linked_taginfo G__G__sigprocLN_TTimeStamp;
extern G__linked_taginfo G__G__sigprocLN_TSnRejectBadClocksMod;
extern G__linked_taginfo G__G__sigprocLN_TSnRejectEarlyEvtsMod;
extern G__linked_taginfo G__G__sigprocLN_TH2;
extern G__linked_taginfo G__G__sigprocLN_TSnFPNCalibSet;
extern G__linked_taginfo G__G__sigprocLN_TSnFPNCalcMod;
extern G__linked_taginfo G__G__sigprocLN_TSnFPNSubMod;
extern G__linked_taginfo G__G__sigprocLN_TSnDualGainCalibSet;
extern G__linked_taginfo G__G__sigprocLN_TSnCalWvData;
extern G__linked_taginfo G__G__sigprocLN_TSnDigitizerCalibMod;
extern G__linked_taginfo G__G__sigprocLN_TSnSaveCalibDataMod;
extern G__linked_taginfo G__G__sigprocLN_TSnCalcAbsTimeMod;
extern G__linked_taginfo G__G__sigprocLN_TCanvas;
extern G__linked_taginfo G__G__sigprocLN_TParameterlEboolgR;
extern G__linked_taginfo G__G__sigprocLN_TSnFindTimeLimitsMod;
extern G__linked_taginfo G__G__sigprocLN_TParameterlEdoublegR;
extern G__linked_taginfo G__G__sigprocLN_TSnFindEvtNumLimitsMod;
extern G__linked_taginfo G__G__sigprocLN_TParameterlEunsignedsPintgR;
extern G__linked_taginfo G__G__sigprocLN_TParameterlEunsignedsPintgRcLcLEStatusBits;
extern G__linked_taginfo G__G__sigprocLN_TGraph;
extern G__linked_taginfo G__G__sigprocLN_TGraphErrors;
extern G__linked_taginfo G__G__sigprocLN_TH1F;
extern G__linked_taginfo G__G__sigprocLN_TH2F;
extern G__linked_taginfo G__G__sigprocLN_TSnPlotEvtRateMod;
extern G__linked_taginfo G__G__sigprocLN_pairlEunsignedsPintcOdoublegR;
extern G__linked_taginfo G__G__sigprocLN_vectorlEpairlEunsignedsPintcOdoublegRcOallocatorlEpairlEunsignedsPintcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__G__sigprocLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOdoublegRcOallocatorlEpairlEunsignedsPintcOdoublegRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__sigprocLN_TSnPlotWaveformsMod;
extern G__linked_taginfo G__G__sigprocLN_TGObject;
extern G__linked_taginfo G__G__sigprocLN_TQObject;
extern G__linked_taginfo G__G__sigprocLN_TQObjSender;
extern G__linked_taginfo G__G__sigprocLN_TGWindow;
extern G__linked_taginfo G__G__sigprocLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__G__sigprocLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__G__sigprocLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__sigprocLN_TGFrame;
extern G__linked_taginfo G__G__sigprocLN_TGCompositeFrame;
extern G__linked_taginfo G__G__sigprocLN_TGTextButton;
extern G__linked_taginfo G__G__sigprocLN_TGVerticalFrame;
extern G__linked_taginfo G__G__sigprocLN_TGHorizontalFrame;
extern G__linked_taginfo G__G__sigprocLN_TGMainFrame;
extern G__linked_taginfo G__G__sigprocLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__G__sigprocLN_TSnEvtGuiCanvFrame;
extern G__linked_taginfo G__G__sigprocLN_TSnEvtGuiCanvFramecLcLEButtonIds;
extern G__linked_taginfo G__G__sigprocLN_TSnEvtGuiSeleFrame;
extern G__linked_taginfo G__G__sigprocLN_TSnEvtGuiDataGuru;
extern G__linked_taginfo G__G__sigprocLN_TSnEvtGuiMainFrame;
extern G__linked_taginfo G__G__sigprocLN_TGCheckButton;
extern G__linked_taginfo G__G__sigprocLN_TGRadioButton;
extern G__linked_taginfo G__G__sigprocLN_TGButtonGroup;
extern G__linked_taginfo G__G__sigprocLN_TGLabel;
extern G__linked_taginfo G__G__sigprocLN_TGNumberEntry;
extern G__linked_taginfo G__G__sigprocLN_TGTab;
extern G__linked_taginfo G__G__sigprocLN_TGComboBox;
extern G__linked_taginfo G__G__sigprocLN_TSnEvtGuiSeleFramecLcLEButtonIds;
extern G__linked_taginfo G__G__sigprocLN_TGFileDialog;
extern G__linked_taginfo G__G__sigprocLN_TSnGCanvasSaveDialog;
extern G__linked_taginfo G__G__sigprocLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__G__sigprocLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__sigprocLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR;
extern G__linked_taginfo G__G__sigprocLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__sigprocLN_TSnRejectBadVoltTimesMod;
extern G__linked_taginfo G__G__sigprocLN_TSnPlotPowerReadingsMod;
extern G__linked_taginfo G__G__sigprocLN_TSnPlotAdcDists;
extern G__linked_taginfo G__G__sigprocLN_TMap;
extern G__linked_taginfo G__G__sigprocLN_TSnCalDatModule;
extern G__linked_taginfo G__G__sigprocLN_TSnCalDatModulecLcLAdrWrap_t;
extern G__linked_taginfo G__G__sigprocLN_TF1;
extern G__linked_taginfo G__G__sigprocLN_TSnFilterWaveformMod;
extern G__linked_taginfo G__G__sigprocLN_TSnStopPosnSet;
extern G__linked_taginfo G__G__sigprocLN_TSnStopFindRms;
extern G__linked_taginfo G__G__sigprocLN_TSnShiftCalWvDataMod;
extern G__linked_taginfo G__G__sigprocLN_TSnMakeShiftTree;
extern G__linked_taginfo G__G__sigprocLN_TSnPruneBadEvtsMod;
extern G__linked_taginfo G__G__sigprocLN_TSnFFTCalcMod;
extern G__linked_taginfo G__G__sigprocLN_TSnFindWaveformEnvelopeMod;

/* STUB derived class for protected member access */
typedef TParameter<unsigned int> G__TParameterlEunsignedsPintgR;
