/********************************************************************
* reco/G__reco.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error reco/G__reco.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__reco();
extern void G__cpp_setup_inheritanceG__reco();
extern void G__cpp_setup_typetableG__reco();
extern void G__cpp_setup_memvarG__reco();
extern void G__cpp_setup_globalG__reco();
extern void G__cpp_setup_memfuncG__reco();
extern void G__cpp_setup_funcG__reco();
extern void G__set_cpp_environmentG__reco();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "reco/NSnChanCorl.h"
#include "reco/TSnMinimizer.h"
#include "reco/TSnFittingModule.h"
#include "reco/TSnChanTimeCorlMod.h"
#include "reco/TSnFitChanOffsetMod.h"
#include "reco/TSnChanTimeCorlAltEvtsMod.h"
#include "reco/TSnFitChanOffsetAltEvtsMod.h"
#include "reco/TSnAngleFromChanCorlMod.h"
#include "reco/TSnAngleFromSingleChanOffsets.h"
#include "reco/TSnSaveRecoResultsMod.h"
#include "reco/TSnSaveCorlDataMod.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__recoLN_TClass;
extern G__linked_taginfo G__G__recoLN_TBuffer;
extern G__linked_taginfo G__G__recoLN_TMemberInspector;
extern G__linked_taginfo G__G__recoLN_TObject;
extern G__linked_taginfo G__G__recoLN_TNamed;
extern G__linked_taginfo G__G__recoLN_TString;
extern G__linked_taginfo G__G__recoLN_ROOT;
extern G__linked_taginfo G__G__recoLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__recoLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__recoLN_TObjArray;
extern G__linked_taginfo G__G__recoLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__recoLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__recoLN_TArrayD;
extern G__linked_taginfo G__G__recoLN_TVector3;
extern G__linked_taginfo G__G__recoLN_TSnInterp1DWvData;
extern G__linked_taginfo G__G__recoLN_NSnChanCorl;
extern G__linked_taginfo G__G__recoLN_ROOTcLcLMath;
extern G__linked_taginfo G__G__recoLN_ROOTcLcLMathcLcLMinimizer;
extern G__linked_taginfo G__G__recoLN_ROOTcLcLMathcLcLFunctor;
extern G__linked_taginfo G__G__recoLN_TSnMinimizer;
extern G__linked_taginfo G__G__recoLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__recoLN_TTask;
extern G__linked_taginfo G__G__recoLN_TTree;
extern G__linked_taginfo G__G__recoLN_vectorlETAMBranchInfocLcLBranchPtr_tmUcOallocatorlETAMBranchInfocLcLBranchPtr_tmUgRsPgR;
extern G__linked_taginfo G__G__recoLN_reverse_iteratorlEvectorlETAMBranchInfocLcLBranchPtr_tmUcOallocatorlETAMBranchInfocLcLBranchPtr_tmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__recoLN_TAModule;
extern G__linked_taginfo G__G__recoLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__G__recoLN_vectorlETIteratormUcOallocatorlETIteratormUgRsPgR;
extern G__linked_taginfo G__G__recoLN_reverse_iteratorlEvectorlETIteratormUcOallocatorlETIteratormUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__recoLN_TSnFittingModule;
extern G__linked_taginfo G__G__recoLN_TMap;
extern G__linked_taginfo G__G__recoLN_TSnCalWvData;
extern G__linked_taginfo G__G__recoLN_TSnCalDatModule;
extern G__linked_taginfo G__G__recoLN_TSnChanTimeCorlMod;
extern G__linked_taginfo G__G__recoLN_TSnFitChanOffsetMod;
extern G__linked_taginfo G__G__recoLN_TSnChanTimeCorlAltEvtsMod;
extern G__linked_taginfo G__G__recoLN_TSnChanTimeCorlAltEvtsModcLcLECorlType_t;
extern G__linked_taginfo G__G__recoLN_TNtuple;
extern G__linked_taginfo G__G__recoLN_TSnEventMetadata;
extern G__linked_taginfo G__G__recoLN_TSnEventHeader;
extern G__linked_taginfo G__G__recoLN_TSnFitChanOffsetAltEvtsMod;
extern G__linked_taginfo G__G__recoLN_TSnFitChanOffsetAltEvtsModcLcLEPars_t;
extern G__linked_taginfo G__G__recoLN_TSnFitChanOffsetAltEvtsModcLcLEFitType_t;
extern G__linked_taginfo G__G__recoLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__recoLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__recoLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__recoLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__recoLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__recoLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__recoLN_TSnRecoChanOffsets;
extern G__linked_taginfo G__G__recoLN_TSnGeoStnSite;
extern G__linked_taginfo G__G__recoLN_TSnAngleFromChanCorlMod;
extern G__linked_taginfo G__G__recoLN_TSnAngleFromChanCorlModcLcLEPars_t;
extern G__linked_taginfo G__G__recoLN_TSnRecoSingleChanOffsetSet;
extern G__linked_taginfo G__G__recoLN_TSnAngleFromSingleChanOffsets;
extern G__linked_taginfo G__G__recoLN_TSnAngleFromSingleChanOffsetscLcLEPars_t;
extern G__linked_taginfo G__G__recoLN_TSnSaveRecoResultsMod;
extern G__linked_taginfo G__G__recoLN_TSnSaveRecoResultsModcLcLTSnRecoResultWrapper;
extern G__linked_taginfo G__G__recoLN_TSnSaveCorlDataMod;

/* STUB derived class for protected member access */
