/********************************************************************
* util/G__util.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error util/G__util.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__util();
extern void G__cpp_setup_inheritanceG__util();
extern void G__cpp_setup_typetableG__util();
extern void G__cpp_setup_memvarG__util();
extern void G__cpp_setup_globalG__util();
extern void G__cpp_setup_memfuncG__util();
extern void G__cpp_setup_funcG__util();
extern void G__set_cpp_environmentG__util();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "util/TSnAxisDetails.h"
#include "util/TSnPlotBrowser.h"
#include "util/TSnMath.h"
#include "util/TSnSpectral.h"
#include "TBranch.h"
#include "TH1.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__utilLN_TClass;
extern G__linked_taginfo G__G__utilLN_TBuffer;
extern G__linked_taginfo G__G__utilLN_TMemberInspector;
extern G__linked_taginfo G__G__utilLN_TObject;
extern G__linked_taginfo G__G__utilLN_TNamed;
extern G__linked_taginfo G__G__utilLN_TString;
extern G__linked_taginfo G__G__utilLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__utilLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__utilLN_TList;
extern G__linked_taginfo G__G__utilLN_TObjArray;
extern G__linked_taginfo G__G__utilLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__utilLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__utilLN_THashTable;
extern G__linked_taginfo G__G__utilLN_TSnAxisDetails;
extern G__linked_taginfo G__G__utilLN_TSnAxisDetailscLcLTAxDet;
extern G__linked_taginfo G__G__utilLN_TQObject;
extern G__linked_taginfo G__G__utilLN_TQObjSender;
extern G__linked_taginfo G__G__utilLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__utilLN_TArrayI;
extern G__linked_taginfo G__G__utilLN_THashList;
extern G__linked_taginfo G__G__utilLN_TGLayoutHints;
extern G__linked_taginfo G__G__utilLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__G__utilLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__G__utilLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__utilLN_TCanvas;
extern G__linked_taginfo G__G__utilLN_TH1F;
extern G__linked_taginfo G__G__utilLN_TGMainFrame;
extern G__linked_taginfo G__G__utilLN_TGVerticalFrame;
extern G__linked_taginfo G__G__utilLN_TGCanvas;
extern G__linked_taginfo G__G__utilLN_TSnPlotBrowser;
extern G__linked_taginfo G__G__utilLN_TSnPlotBrowsercLcLEPadOpts;
extern G__linked_taginfo G__G__utilLN_TSnPlotBrowsercLcLTArPlotSet;
extern G__linked_taginfo G__G__utilLN_TH1;
extern G__linked_taginfo G__G__utilLN_TSnMath;
extern G__linked_taginfo G__G__utilLN_TBranch;
extern G__linked_taginfo G__G__utilLN_TGraph;
extern G__linked_taginfo G__G__utilLN_TSnSpectral;
extern G__linked_taginfo G__G__utilLN_TSnSpectralcLcLEWinType_t;
extern G__linked_taginfo G__G__utilLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__utilLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__utilLN_TH1D;

/* STUB derived class for protected member access */
