/********************************************************************
* commacts/G__commacts.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error commacts/G__commacts.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__commacts();
extern void G__cpp_setup_inheritanceG__commacts();
extern void G__cpp_setup_typetableG__commacts();
extern void G__cpp_setup_memvarG__commacts();
extern void G__cpp_setup_globalG__commacts();
extern void G__cpp_setup_memfuncG__commacts();
extern void G__cpp_setup_funcG__commacts();
extern void G__set_cpp_environmentG__commacts();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "commacts/TSnCommActHiRate.h"
#include "commacts/TSnCommActConfResend.h"
#include "commacts/TSnCommActSendQueued.h"
#include "commacts/TSnCommActSendNoConf.h"
#include "commacts/TSnCommActSendPeriodic.h"
#include "commacts/TSnCommFiActTransComplete.h"
#include "commacts/TSnCommFiActStopTrans.h"
#include "commacts/TSnCommFiActDeleteRun.h"
#include "commacts/TSnCommFiActDeleteAllData.h"
#include "commacts/TSnCommFiActRequestRun.h"
#include "commacts/TSnCommFiActNoReplyHndshk.h"
#include "commacts/TSnCommFiActSendQueued.h"
#include "commacts/TSnCAGuiActorFrame.h"
#include "commacts/TSnCAGuiActsList.h"
#include "commacts/TSnCAGuiActsAvailList.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__commactsLN_TClass;
extern G__linked_taginfo G__G__commactsLN_TBuffer;
extern G__linked_taginfo G__G__commactsLN_TMemberInspector;
extern G__linked_taginfo G__G__commactsLN_TObject;
extern G__linked_taginfo G__G__commactsLN_TString;
extern G__linked_taginfo G__G__commactsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__commactsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__commactsLN_TObjArray;
extern G__linked_taginfo G__G__commactsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__commactsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__commactsLN_TTimeStamp;
extern G__linked_taginfo G__G__commactsLN_TSnCommObject;
extern G__linked_taginfo G__G__commactsLN_TSnCommActor;
extern G__linked_taginfo G__G__commactsLN_TSnCommAction;
extern G__linked_taginfo G__G__commactsLN_TSnCommIncFile;
extern G__linked_taginfo G__G__commactsLN_TSnCommIncStatus;
extern G__linked_taginfo G__G__commactsLN_TSnCommStatusAction;
extern G__linked_taginfo G__G__commactsLN_TSnDAQConfig;
extern G__linked_taginfo G__G__commactsLN_TSnRunInfo;
extern G__linked_taginfo G__G__commactsLN_TSnCommActHiRate;
extern G__linked_taginfo G__G__commactsLN_TSnCommActConfResend;
extern G__linked_taginfo G__G__commactsLN_TSnCommActSendQueued;
extern G__linked_taginfo G__G__commactsLN_TSnCommActSendNoConf;
extern G__linked_taginfo G__G__commactsLN_TSnCommActSendPeriodic;
extern G__linked_taginfo G__G__commactsLN_TSnCommFileAction;
extern G__linked_taginfo G__G__commactsLN_TSnCommFiActTransComplete;
extern G__linked_taginfo G__G__commactsLN_TSnCommFiActStopTrans;
extern G__linked_taginfo G__G__commactsLN_TSnCommFiActDeleteRun;
extern G__linked_taginfo G__G__commactsLN_TSnCommFiActDeleteAllData;
extern G__linked_taginfo G__G__commactsLN_TSnCommFiActRequestRun;
extern G__linked_taginfo G__G__commactsLN_TSnCommFiActNoReplyHndshk;
extern G__linked_taginfo G__G__commactsLN_TSnCommFiActSendQueued;
extern G__linked_taginfo G__G__commactsLN_TSnCAGuiActsList;
extern G__linked_taginfo G__G__commactsLN_TSnCAGuiActsAvailList;
extern G__linked_taginfo G__G__commactsLN_TGClient;
extern G__linked_taginfo G__G__commactsLN_TGObject;
extern G__linked_taginfo G__G__commactsLN_TQObject;
extern G__linked_taginfo G__G__commactsLN_TGWindow;
extern G__linked_taginfo G__G__commactsLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__G__commactsLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__G__commactsLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__commactsLN_TGFrame;
extern G__linked_taginfo G__G__commactsLN_TGCompositeFrame;
extern G__linked_taginfo G__G__commactsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__commactsLN_TGTextButton;
extern G__linked_taginfo G__G__commactsLN_TGLabel;
extern G__linked_taginfo G__G__commactsLN_TSnCAGuiActorFrame;
extern G__linked_taginfo G__G__commactsLN_TGWidget;
extern G__linked_taginfo G__G__commactsLN_TGListBox;

/* STUB derived class for protected member access */
