###
# File generated by "add-prog.sh prog/dbExampleStringKeyHardwareModel.cxx".
#
# $Id$
###

# List here objects that should be explicitly built into the executable.
# NOTE: DO NOT include "dbExampleStringKeyHardwareModel.o" in this list.
dbExampleStringKeyHardwareModelOBJS := \
	

# List here library paths (-L) and libraries (-l) that the executable
# should be linked with.
dbExampleStringKeyHardwareModelLINK := \
	`root-config --libs` \
	-L$(SNS)/lib -ldb -ldbdat -lpqdb \
	-L$(PQXXLIB) -lpqxx \
	
# By default the general ROOT libraries are inlcuded. Remove this if necessary.

# For all ARK libraries, use:
#prog/dbExampleStringKeyHardwareModelLINK := \
#	`build/ark-libs.sh` \

# For antares-daq libraries:
#prog/dbExampleStringKeyHardwareModelLINK := \
#	-L$(ANTDAQLIB) -lantccROOT -ldataformatROOT \

# For Physics libraries:
#prog/dbExampleStringKeyHardwareModelLINK := \
#	-L$(PHYSLIB) -lPhysics$(PHYSVER) \

################################################################################
# DO NOT EDIT BELOW
################################################################################
bin/dbExampleStringKeyHardwareModel.$(EXEEXT):: prog/dbExampleStringKeyHardwareModel.o $(dbExampleStringKeyHardwareModelOBJS) prog/dbExampleStringKeyHardwareModel.mk
	@$(MAKEEXE) $(MAKELIB) $(PLATFORM) $(LD) "$(LDFLAGS)" \
	"$(EXEFLAGS)" $@ "$<" \
	"$(dbExampleStringKeyHardwareModelOBJS) $(dbExampleStringKeyHardwareModelLINK)"

