/********************************************************************
* db/G__db.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error db/G__db.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__db();
extern void G__cpp_setup_inheritanceG__db();
extern void G__cpp_setup_typetableG__db();
extern void G__cpp_setup_memvarG__db();
extern void G__cpp_setup_globalG__db();
extern void G__cpp_setup_memfuncG__db();
extern void G__cpp_setup_funcG__db();
extern void G__set_cpp_environmentG__db();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "db/TSnDatabase.h"
#include "db/NSnDatabase.h"
#include "db/TSnConnection.h"
#include "db/TSnDbKey.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__dbLN_TClass;
extern G__linked_taginfo G__G__dbLN_TBuffer;
extern G__linked_taginfo G__G__dbLN_TMemberInspector;
extern G__linked_taginfo G__G__dbLN_TObject;
extern G__linked_taginfo G__G__dbLN_TNamed;
extern G__linked_taginfo G__G__dbLN_TString;
extern G__linked_taginfo G__G__dbLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__dbLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__dbLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__dbLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__dbLN_THashTable;
extern G__linked_taginfo G__G__dbLN_TMap;
extern G__linked_taginfo G__G__dbLN_NSnDatabase;
extern G__linked_taginfo G__G__dbLN_NSnDatabasecLcLEWriteType;
extern G__linked_taginfo G__G__dbLN_TSnConnection;
extern G__linked_taginfo G__G__dbLN_TSnDbKey;
extern G__linked_taginfo G__G__dbLN_TSnDatabase;
extern G__linked_taginfo G__G__dbLN_TTimeStamp;

/* STUB derived class for protected member access */
