/********************************************************************
* geo/G__geo.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error geo/G__geo.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__geo();
extern void G__cpp_setup_inheritanceG__geo();
extern void G__cpp_setup_typetableG__geo();
extern void G__cpp_setup_memvarG__geo();
extern void G__cpp_setup_globalG__geo();
extern void G__cpp_setup_memfuncG__geo();
extern void G__cpp_setup_funcG__geo();
extern void G__set_cpp_environmentG__geo();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "geo/TSnGeoStnSite.h"
#include "geo/TSnGeoDAQBox.h"
#include "geo/TSnGeoLPDA.h"
#include "geo/NSnGeoMaterials.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__geoLN_TClass;
extern G__linked_taginfo G__G__geoLN_TBuffer;
extern G__linked_taginfo G__G__geoLN_TMemberInspector;
extern G__linked_taginfo G__G__geoLN_TObject;
extern G__linked_taginfo G__G__geoLN_TNamed;
extern G__linked_taginfo G__G__geoLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__geoLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__geoLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__geoLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__geoLN_TGeoAtt;
extern G__linked_taginfo G__G__geoLN_TAttLine;
extern G__linked_taginfo G__G__geoLN_TAttFill;
extern G__linked_taginfo G__G__geoLN_TAtt3D;
extern G__linked_taginfo G__G__geoLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__geoLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR;
extern G__linked_taginfo G__G__geoLN_TGeoVolume;
extern G__linked_taginfo G__G__geoLN_TGeoNode;
extern G__linked_taginfo G__G__geoLN_TGeoManager;
extern G__linked_taginfo G__G__geoLN_TGeoVolumeAssembly;
extern G__linked_taginfo G__G__geoLN_vectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgR;
extern G__linked_taginfo G__G__geoLN_reverse_iteratorlEvectorlETGeoVolumeAssemblycLcLThreadData_tmUcOallocatorlETGeoVolumeAssemblycLcLThreadData_tmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__geoLN_TVector3;
extern G__linked_taginfo G__G__geoLN_TSnGeoStnSite;
extern G__linked_taginfo G__G__geoLN_TSnGeoDAQBox;
extern G__linked_taginfo G__G__geoLN_TSnGeoLPDA;
extern G__linked_taginfo G__G__geoLN_NSnGeoMaterials;
extern G__linked_taginfo G__G__geoLN_NSnGeoMaterialscLcLEAriannMedium_t;

/* STUB derived class for protected member access */
