/********************************************************************
* sigprocdat/G__sigprocdat.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error sigprocdat/G__sigprocdat.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__sigprocdat();
extern void G__cpp_setup_inheritanceG__sigprocdat();
extern void G__cpp_setup_typetableG__sigprocdat();
extern void G__cpp_setup_memvarG__sigprocdat();
extern void G__cpp_setup_globalG__sigprocdat();
extern void G__cpp_setup_memfuncG__sigprocdat();
extern void G__cpp_setup_funcG__sigprocdat();
extern void G__set_cpp_environmentG__sigprocdat();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "sigprocdat/TSnCalibObject.h"
#include "sigprocdat/TSnCalibSet.h"
#include "sigprocdat/TSnPerSampCalibSet.h"
#include "sigprocdat/TSnPerCardCalibSet.h"
#include "sigprocdat/TSnFPNCalibVal.h"
#include "sigprocdat/TSnFPNCalibSet.h"
#include "sigprocdat/TSnGainCalibVal.h"
#include "sigprocdat/TSnDualGainCalib.h"
#include "sigprocdat/TSnDualGainCalibSet.h"
#include "sigprocdat/TSnCalWvData.h"
#include "sigprocdat/TSnInterp1DWvData.h"
#include "sigprocdat/TSnInterp1DSpline3.h"
#include "sigprocdat/TSnStopPosnSet.h"
#include "sigprocdat/TSnCalFFTData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__sigprocdatLN_TClass;
extern G__linked_taginfo G__G__sigprocdatLN_TBuffer;
extern G__linked_taginfo G__G__sigprocdatLN_TMemberInspector;
extern G__linked_taginfo G__G__sigprocdatLN_TObject;
extern G__linked_taginfo G__G__sigprocdatLN_TNamed;
extern G__linked_taginfo G__G__sigprocdatLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__sigprocdatLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__sigprocdatLN_TObjArray;
extern G__linked_taginfo G__G__sigprocdatLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__sigprocdatLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__sigprocdatLN_TSnCalibObject;
extern G__linked_taginfo G__G__sigprocdatLN_TSnCalibSet;
extern G__linked_taginfo G__G__sigprocdatLN_TSnPerSampCalibSet;
extern G__linked_taginfo G__G__sigprocdatLN_TSnPerCardCalibSet;
extern G__linked_taginfo G__G__sigprocdatLN_TSnFPNCalibVal;
extern G__linked_taginfo G__G__sigprocdatLN_TSnFPNCalibSet;
extern G__linked_taginfo G__G__sigprocdatLN_TSnGainCalibVal;
extern G__linked_taginfo G__G__sigprocdatLN_TSnDualGainCalib;
extern G__linked_taginfo G__G__sigprocdatLN_TSnDualGainCalibSet;
extern G__linked_taginfo G__G__sigprocdatLN_TArrayF;
extern G__linked_taginfo G__G__sigprocdatLN_TGraph;
extern G__linked_taginfo G__G__sigprocdatLN_TSnCalWvData;
extern G__linked_taginfo G__G__sigprocdatLN_TSnInterp1DWvData;
extern G__linked_taginfo G__G__sigprocdatLN_TSpline3;
extern G__linked_taginfo G__G__sigprocdatLN_TSnInterp1DSpline3;
extern G__linked_taginfo G__G__sigprocdatLN_TSnStopPosnSet;
extern G__linked_taginfo G__G__sigprocdatLN_TSnCalFFTData;

/* STUB derived class for protected member access */
